name: Mitska
favicon: null
layout_spectrum: 0.56079
typography_spectrum: 0.45489
title: The Illustrious Mitska
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fff0f6'
    - '#b40367'
    - '#706fa1'
    - '#e36795'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
