name: Mitska
favicon: null
layout_spectrum: 0.74879
typography_spectrum: 0.45489
title: The Illustrious Mitska
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fff0f6'
    - '#b40367'
    - '#706fa1'
    - '#e36795'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
